"""add reference_video_path to session

Revision ID: 39198357a33d
Revises: 46bd67da7c3a
Create Date: 2026-05-03 17:05:29.277219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39198357a33d'
down_revision: Union[str, None] = '46bd67da7c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('reference_video_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'reference_video_path')
    # ### end Alembic commands ###
