"""add reference video path

Revision ID: 46bd67da7c3a
Revises: c9a6a6b1315f
Create Date: 2026-05-03 16:54:20.278303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bd67da7c3a'
down_revision: Union[str, None] = 'c9a6a6b1315f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
