"""facial comparison fields

Revision ID: 6d2d2f2afd47
Revises: 39198357a33d
Create Date: 2026-05-03 17:08:06.722046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d2d2f2afd47'
down_revision: Union[str, None] = '39198357a33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_results', sa.Column('ref_dominant', sa.String(length=50), nullable=True))
    op.add_column('facial_results', sa.Column('ref_percentages', sa.JSON(), nullable=True))
    op.add_column('facial_results', sa.Column('comparison_score', sa.Float(), nullable=True))
    op.add_column('facial_results', sa.Column('grade', sa.String(length=100), nullable=True))
    op.add_column('facial_results', sa.Column('score_components', sa.JSON(), nullable=True))
    op.drop_column('facial_results', 'reference_video_path')
    op.drop_column('facial_results', 'word_scores')
    op.drop_column('facial_results', 'pronunciation_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_results', sa.Column('pronunciation_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('facial_results', sa.Column('word_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('facial_results', sa.Column('reference_video_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('facial_results', 'score_components')
    op.drop_column('facial_results', 'grade')
    op.drop_column('facial_results', 'comparison_score')
    op.drop_column('facial_results', 'ref_percentages')
    op.drop_column('facial_results', 'ref_dominant')
    # ### end Alembic commands ###
