"""add word scores

Revision ID: 7afb0955cf9f
Revises: 0cb72196180f
Create Date: 2026-05-02 00:15:49.554518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afb0955cf9f'
down_revision: Union[str, None] = '0cb72196180f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speech_results', sa.Column('word_scores', sa.JSON(), nullable=True))
    op.add_column('speech_results', sa.Column('pronunciation_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speech_results', 'pronunciation_summary')
    op.drop_column('speech_results', 'word_scores')
    # ### end Alembic commands ###
