"""add annotated video and emotion percentages

Revision ID: b6ac060c9b5d
Revises: f39647e17f20
Create Date: 2026-05-03 12:57:59.373174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ac060c9b5d'
down_revision: Union[str, None] = 'f39647e17f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_results', sa.Column('emotion_percentages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facial_results', 'emotion_percentages')
    # ### end Alembic commands ###
