"""add speech pause and filler fields

Revision ID: c3a9f2c8b0e1
Revises: 7afb0955cf9f
Create Date: 2026-05-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a9f2c8b0e1'
down_revision: Union[str, None] = '7afb0955cf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speech_results', sa.Column('pauses', sa.JSON(), nullable=True))
    op.add_column('speech_results', sa.Column('pause_stats', sa.JSON(), nullable=True))
    op.add_column('speech_results', sa.Column('filler_words', sa.JSON(), nullable=True))
    op.add_column('speech_results', sa.Column('filler_counts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speech_results', 'filler_counts')
    op.drop_column('speech_results', 'filler_words')
    op.drop_column('speech_results', 'pause_stats')
    op.drop_column('speech_results', 'pauses')
    # ### end Alembic commands ###
