"""add reference video path

Revision ID: c9a6a6b1315f
Revises: b6ac060c9b5d
Create Date: 2026-05-03 16:50:16.979063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a6a6b1315f'
down_revision: Union[str, None] = 'b6ac060c9b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_results', sa.Column('reference_video_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facial_results', 'reference_video_path')
    # ### end Alembic commands ###
