"""add pronunciation fields

Revision ID: e5275bb474ee
Revises: cb71113de778
Create Date: 2026-04-27 01:48:49.284386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5275bb474ee'
down_revision: Union[str, None] = 'cb71113de778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_results', sa.Column('word_scores', sa.JSON(), nullable=True))
    op.add_column('facial_results', sa.Column('pronunciation_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facial_results', 'pronunciation_summary')
    op.drop_column('facial_results', 'word_scores')
    # ### end Alembic commands ###
