"""add annotated video path

Revision ID: f39647e17f20
Revises: 7afb0955cf9f
Create Date: 2026-05-03 12:54:19.368280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39647e17f20'
down_revision: Union[str, None] = '7afb0955cf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('annotated_video_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'annotated_video_path')
    # ### end Alembic commands ###
